version: "3.0"
services:
  client:
    build: ./front-end
    ports:
      - 3000:3000
    volumes: 
      - ./front-end:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  elasticsearch:
    image: elasticsearch:6.4.1
    ports:
      - "9200:9200"
    networks:
      - docker_elk
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: kibana:6.4.1
    environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - docker_elk
networks:
  docker_elk:
    driver: bridge
volumes:
  node_modules: